# Generated by Django 4.0.4 on 2022-05-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='locations',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hotelimage',
            old_name='hotels',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='hotels',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='roomimage',
            old_name='rooms',
            new_name='room',
        ),
    ]
