# Generated by Django 4.0.4 on 2022-05-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='hotels',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='reviewimage',
            old_name='reviews',
            new_name='review',
        ),
    ]
