# Generated by Django 4.0.4 on 2022-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.IntegerField(),
        ),
    ]
